name: mrr_reporting
description: ''
version: '0.4'
author: maciej+guides@prophecy.io
language: python
buildSystem: wheel
pipelines:
  pipelines/customers_orders:
    name: customers_orders
    description: ''
    author: maciej+guides@prophecy.io
    mode: batch
    language: python
    createdAt: '2022-06-28 06:52:00'
    datasets:
      inputs:
      - 7750/datasets/orders
      - 7750/datasets/orders_source
      - 7750/datasets/nations
      - 7750/datasets/customers
      - 7750/datasets/regions
      outputs:
      - 7750/datasets/orders_report
    dependencies: {}
datasets:
  datasets/orders:
    name: orders
    description: ''
    author: maciej+guides@prophecy.io
    createdAt: '2022-06-28 07:00:44'
    physicalDatasets:
      dev:
        fabricId: 1436
        datasetType: File
        description: ''
        author: maciej+guides@prophecy.io
        createdAt: '2022-06-28 07:00:44'
  datasets/regions:
    name: regions
    description: ''
    author: maciej+guides@prophecy.io
    createdAt: '2022-06-24 00:16:06'
    physicalDatasets:
      dev:
        fabricId: 1436
        datasetType: File
        description: ''
        author: maciej+guides@prophecy.io
        createdAt: '2022-06-24 00:16:06'
  datasets/customers:
    name: customers_nations
    description: ''
    author: maciej+guides@prophecy.io
    createdAt: '2022-06-24 00:13:42'
    physicalDatasets:
      dev:
        fabricId: 1436
        datasetType: File
        description: ''
        author: maciej+guides@prophecy.io
        createdAt: '2022-06-24 00:13:42'
  datasets/orders_report:
    name: orders_report
    description: ''
    author: maciej+guides@prophecy.io
    createdAt: '2022-06-28 07:07:24'
    physicalDatasets:
      dev:
        fabricId: 1436
        datasetType: Database
        description: ''
        author: maciej+guides@prophecy.io
        createdAt: '2022-06-28 07:07:24'
  datasets/orders_source:
    name: orders_source
    description: ''
    author: maciej+guides@prophecy.io
    createdAt: '2022-06-28 07:01:30'
    physicalDatasets:
      dev:
        fabricId: 1436
        datasetType: File
        description: ''
        author: maciej+guides@prophecy.io
        createdAt: '2022-06-28 07:01:30'
  datasets/nations:
    name: nations
    description: ''
    author: maciej+guides@prophecy.io
    createdAt: '2022-06-24 00:15:36'
    physicalDatasets:
      dev:
        fabricId: 1436
        datasetType: File
        description: ''
        author: maciej+guides@prophecy.io
        createdAt: '2022-06-24 00:15:36'
templates: {}
jobs:
  jobs/monthly_customer_spendings:
    name: monthly_customer_spendings
    description: ''
    fabricUID: 1436
    scheduler:
      Databricks: {}
    jobSize: small
    scheduleCron: 0 0 0 1 * ? *
    timeout: null
    alerting:
      emails: maciej@prophecy.io
      onStart: false
      onSuccess: true
      onFailure: true
    pipelines:
    - 7750/pipelines/customers_orders
    enabled: null
    createdAt: '2022-06-28 07:08:56'
    author: maciej+guides@prophecy.io
libraries: []
subgraphs:
  subgraphs/customer_details:
    name: customer_details
    description: ''
    author: maciej+guides@prophecy.io
    language: python
    createdAt: '2022-06-24 00:16:45'
dependencies: []
