name: mrr_reporting
description: ''
version: '0.5'
author: maciej+guides@prophecy.io
language: python
buildSystem: wheel
pipelines:
  pipelines/customers_spendings:
    name: customers_spendings
    description: ''
    author: maciej+guides@prophecy.io
    mode: batch
    language: python
    createdAt: '2022-06-28 23:00:48'
    datasets:
      inputs:
      - 7750/datasets/customers_source
      - 7750/datasets/orders_source
      - 7750/datasets/nations
      - 7750/datasets/customers
      - 7750/datasets/regions
      outputs:
      - 7750/datasets/report
    dependencies: {}
datasets:
  datasets/regions:
    name: regions
    description: ''
    author: maciej+guides@prophecy.io
    createdAt: '2022-06-24 00:16:06'
    physicalDatasets:
      dev:
        fabricId: 1436
        datasetType: File
        description: ''
        author: maciej+guides@prophecy.io
        createdAt: '2022-06-24 00:16:06'
  datasets/customers:
    name: customers_nations
    description: ''
    author: maciej+guides@prophecy.io
    createdAt: '2022-06-24 00:13:42'
    physicalDatasets:
      dev:
        fabricId: 1436
        datasetType: File
        description: ''
        author: maciej+guides@prophecy.io
        createdAt: '2022-06-24 00:13:42'
  datasets/orders_source:
    name: orders_source
    description: ''
    author: maciej+guides@prophecy.io
    createdAt: '2022-06-28 23:04:18'
    physicalDatasets:
      dev:
        fabricId: 1436
        datasetType: File
        description: ''
        author: maciej+guides@prophecy.io
        createdAt: '2022-06-28 23:04:18'
  datasets/customers_source:
    name: customers_source
    description: ''
    author: maciej+guides@prophecy.io
    createdAt: '2022-06-28 23:03:43'
    physicalDatasets:
      dev:
        fabricId: 1436
        datasetType: File
        description: ''
        author: maciej+guides@prophecy.io
        createdAt: '2022-06-28 23:03:43'
  datasets/nations:
    name: nations
    description: ''
    author: maciej+guides@prophecy.io
    createdAt: '2022-06-24 00:15:36'
    physicalDatasets:
      dev:
        fabricId: 1436
        datasetType: File
        description: ''
        author: maciej+guides@prophecy.io
        createdAt: '2022-06-24 00:15:36'
  datasets/report:
    name: report
    description: ''
    author: maciej+guides@prophecy.io
    createdAt: '2022-06-28 23:08:48'
    physicalDatasets:
      dev:
        fabricId: 1436
        datasetType: Database
        description: ''
        author: maciej+guides@prophecy.io
        createdAt: '2022-06-28 23:08:48'
templates: {}
jobs:
  jobs/monthly_reporting:
    name: monthly_reporting
    description: ''
    fabricUID: 1436
    scheduler:
      Databricks: {}
    jobSize: small
    scheduleCron: 0 0 0 1 * ? *
    timeout: null
    alerting:
      emails: maciej@prophecy.io
      onStart: false
      onSuccess: true
      onFailure: true
    pipelines:
    - 7750/pipelines/customers_spendings
    enabled: true
    createdAt: '2022-06-28 23:10:21'
    author: maciej+guides@prophecy.io
libraries: []
subgraphs:
  subgraphs/customer_details:
    name: customer_details
    description: ''
    author: maciej+guides@prophecy.io
    language: python
    createdAt: '2022-06-24 00:16:45'
dependencies: []
